# Generated by Django 5.2.5 on 2025-10-24 17:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_is_recurring_task_recurrence_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurring_task_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
